# Generated by Django 5.2.6 on 2025-09-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_booking_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='email',
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('Airport Transfer', 'Airport Transfer'), ('Point to Point', 'Point to Point'), ('Hourly', 'Hourly'), ('Other', 'Other')], default='Point to Point', max_length=50, verbose_name='Service Type'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(choices=[('TC', 'Town Car (Self)'), ('TD', 'Town Car (Delegated)'), ('SUV', 'SUV')], default='TC', max_length=3),
        ),
    ]
