# Generated by Django 5.2.6 on 2025-09-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_booking_service_remove_driver_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='booking',
            name='delegated_driver_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Delegated Driver Name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('AT', 'Airport Transfer'), ('PT', 'Point to Point'), ('HR', 'Hourly'), ('OT', 'Other')], default='PT', max_length=2, verbose_name='Service Type'),
        ),
    ]
