# Generated by Django 5.2.6 on 2025-09-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_delete_service_booking_delegated_driver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='home_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='home_state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='home_street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='home_zipcode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
