# Generated by Django 5.2.6 on 2025-09-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_client_client_notes_client_home_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='airport_code',
            field=models.CharField(blank=True, choices=[('JFK', 'JFK'), ('LGA', 'LGA'), ('EWR', 'EWR'), ('HPN', 'HPN'), ('SWF', 'SWF'), ('ISP', 'ISP'), ('Other', 'Other')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
