# Generated by Django 5.2.6 on 2025-10-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_booking_airport_code_alter_booking_pickup_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('AP', 'Airport Pickup (Airport to Destination)'), ('AD', 'Airport Dropoff (Destination to Airport)'), ('PT', 'Point to Point'), ('HR', 'Hourly'), ('OT', 'Other')], default='PT', max_length=2, verbose_name='Service Type'),
        ),
    ]
